import { runStandardMemorySimulationSet } from "./memoryModelSimulation";

const getTimelinePoint = (timeline, label) => timeline.find((point) => point.label === label);

const buildReportRows = (journeys) => [
  ["Journey", "Day", "Event", "Avg", "Learned avg", "Refresh", "Severe", "Stability", "Notes"],
  ...Object.entries(journeys).flatMap(([journeyName, journey]) =>
    journey.timeline.map((point) => [
      journeyName,
      point.day,
      point.label,
      `${point.averageMastery}%`,
      `${point.learnedAverageMastery}%`,
      `${point.refreshCards}/${point.learnedCards} (${point.refreshRate}%)`,
      point.severeDecayCards,
      `${point.averageStability}d`,
      point.notes,
    ])
  ),
];

const flatMemoryModel = {
  buildNextMemoryRecord(previousRecord = {}, { isCorrect, now }) {
    const previousAttempts = previousRecord.attempts || 0;
    const mastery = isCorrect
      ? Math.min(62, (previousRecord.flatMastery || 0) + 9)
      : Math.max(18, (previousRecord.flatMastery || 35) - 6);

    return {
      attempts: previousAttempts + 1,
      flatMastery: mastery,
      lastSeen: now,
      status: isCorrect ? "correct" : "incorrect",
    };
  },
  calculateCardMastery(record) {
    return record ? record.flatMastery || 0 : 0;
  },
  getMemoryState(record) {
    return {
      stabilityDays: record ? 1 : 0,
    };
  },
};

describe("memory model simulated student journeys", () => {
  test("steady student decays after absence and improves through Memory Repair", () => {
    const { steadyStudent } = runStandardMemorySimulationSet();
    const timeline = steadyStudent.timeline;

    const baseline = getTimelinePoint(timeline, "Day 0: no prior mastery");
    const day3 = getTimelinePoint(timeline, "Day 3: normal review");
    const away = getTimelinePoint(timeline, "Day 7: four days away");
    const repaired = getTimelinePoint(timeline, "Day 8: second repair pass");
    const secondAway = getTimelinePoint(timeline, "Day 14: another six days away");
    const final = getTimelinePoint(timeline, "Day 15: consolidation review");

    expect(baseline.averageMastery).toBe(0);
    expect(day3.learnedCards).toBe(24);
    expect(day3.averageMastery).toBeGreaterThan(away.averageMastery);
    expect(away.refreshRate).toBeGreaterThan(day3.refreshRate);
    expect(repaired.averageMastery).toBeGreaterThan(away.averageMastery);
    expect(repaired.refreshRate).toBeLessThanOrEqual(away.refreshRate);
    expect(secondAway.refreshRate).toBeGreaterThan(repaired.refreshRate);
    expect(final.averageMastery).toBeGreaterThan(secondAway.averageMastery);
    expect(final.refreshRate).toBeLessThan(secondAway.refreshRate);
  });

  test("slacker/recovery student improves but keeps a larger refresh load", () => {
    const { slackerRecoveryStudent, steadyStudent } = runStandardMemorySimulationSet();
    const slackerTimeline = slackerRecoveryStudent.timeline;
    const steadyTimeline = steadyStudent.timeline;

    const weakStart = getTimelinePoint(slackerTimeline, "Day 0: weak first quiz session");
    const skippedDays = getTimelinePoint(slackerTimeline, "Day 5: skipped several days");
    const firstRepair = getTimelinePoint(slackerTimeline, "Day 5: responds to nudge");
    const secondSlip = getTimelinePoint(slackerTimeline, "Day 10: slips again");
    const final = getTimelinePoint(slackerTimeline, "Day 11: follow-up repair");
    const steadyFinal = getTimelinePoint(steadyTimeline, "Day 15: consolidation review");

    expect(weakStart.averageMastery).toBeGreaterThan(0);
    expect(skippedDays.refreshRate).toBeGreaterThanOrEqual(weakStart.refreshRate);
    expect(firstRepair.averageMastery).toBeGreaterThan(skippedDays.averageMastery);
    expect(secondSlip.refreshRate).toBeGreaterThan(firstRepair.refreshRate);
    expect(final.averageMastery).toBeGreaterThan(secondSlip.averageMastery);
    expect(final.refreshRate).toBeGreaterThanOrEqual(steadyFinal.refreshRate);
  });

  test("simulation timelines are reportable for tuning reviews", () => {
    const journeys = runStandardMemorySimulationSet();
    const rows = buildReportRows(journeys);

    if (process.env.MEMORY_SIM_REPORT === "1") {
      // eslint-disable-next-line no-console
      console.log(JSON.stringify(rows, null, 2));
    }

    // Kept as a compact smoke assertion; the markdown review records the readable version.
    expect(rows.length).toBeGreaterThan(15);
    expect(rows[0]).toEqual([
      "Journey",
      "Day",
      "Event",
      "Avg",
      "Learned avg",
      "Refresh",
      "Severe",
      "Stability",
      "Notes",
    ]);
  });

  test("simulation output is generated by the injected memory model, not fixed table data", () => {
    const realJourneys = runStandardMemorySimulationSet();
    const flatJourneys = runStandardMemorySimulationSet({ memory: flatMemoryModel });

    const realFinal = getTimelinePoint(
      realJourneys.steadyStudent.timeline,
      "Day 15: consolidation review"
    );
    const flatFinal = getTimelinePoint(
      flatJourneys.steadyStudent.timeline,
      "Day 15: consolidation review"
    );
    const realAway = getTimelinePoint(realJourneys.steadyStudent.timeline, "Day 7: four days away");
    const flatAway = getTimelinePoint(flatJourneys.steadyStudent.timeline, "Day 7: four days away");

    expect(realFinal.averageMastery).not.toBe(flatFinal.averageMastery);
    expect(realFinal.averageStability).not.toBe(flatFinal.averageStability);
    expect(realAway.refreshRate).not.toBe(flatAway.refreshRate);
  });
});
